### ISSUE TITLE
End support for Node.js < 18 across projects

### ISSUE THREAD

**Issue by danyalaytekin** [pa11y/org#17]
See https://github.com/pa11y/pa11y-webservice-client-node/issues/19#issuecomment-1750614222, and [Node.js's releases page](https://nodejs.dev/en/about/releases/) for key dates.

Each 'Publish' step here will become a PR which includes an update to documentation and metadata.

### Summary

- [x] **[pa11y](https://github.com/pa11y/pa11y)**
    - [x] pa11y/pa11y#664
    - [x] pa11y/pa11y#681
- [x] **[pa11y-ci](https://github.com/pa11y/pa11y-ci)**
    - [x] pa11y/pa11y-ci#231
    - [x] pa11y/pa11y-ci#259
- [ ] **[pa11y-dashboard](https://github.com/pa11y/pa11y-dashboard)**
    - [ ] _Create PR for change_
    - [ ] Publish `5.0.0`
- [ ] **[pa11y-webservice](https://github.com/pa11y/pa11y-webservice)**
    - [x] pa11y/pa11y-webservice#149
    - [ ] pa11y/pa11y-webservice#159
- [x] **[pa11y-webservice-client-node](https://github.com/pa11y/pa11y-webservice-client-node)**
    - [x] pa11y/pa11y-webservice-client-node#19
    - [x] pa11y/pa11y-webservice-client-node#24
- [x] **[pa11y-lint-config](https://github.com/pa11y/pa11y-lint-config)**
    - [x] pa11y/pa11y-lint-config#4
    - [x] pa11y/pa11y-lint-config#8

Stretch goal:

- [ ] **[pa11y.github.io](https://github.com/pa11y/pa11y.github.io)**
