### ISSUE TITLE
Clarify the support policy

### ISSUE THREAD

**Issue by danyalaytekin** [pa11y/org#18]
See comment:

- https://github.com/pa11y/pa11y-webservice-client-node/pull/19#discussion_r1348682283

Perhaps we could also centralise the refined description (not necessarily the tables) and make it shareable, if it will be the same policy for each project, as also discussed by:

- https://github.com/pa11y/org/issues/16

---

Now tracking the rollout:

- [x] pa11y/pa11y#681
- [x] pa11y/pa11y-ci#226
- [x] pa11y/pa11y-lint-config#8
- [x] pa11y/pa11y-webservice#148
- [ ] pa11y/pa11y-webservice-client-node#24
- [ ] pa11y/pa11y-dashboard#320

**Comment by danyalaytekin** [comment]
We've agreed this wording:

> When we release a new major version we will continue to support the previous major version for 6 months.  This support will be limited to fixes for critical bugs and security issues.
