### ISSUE TITLE
Update repo settings and improve their consistency

### ISSUE THREAD

**Issue by danyalaytekin** [pa11y/org#20]
### Revised description

Implement with [github/safe-settings](https://github.com/github/safe-settings) for any option it supports.

#### Part 1

- [ ] Create settings repo
- [ ] Set up and host the app
- [ ] Grant permissions to app
- [ ] Use to configure `pa11y-lint-config`

#### Part 2

If all went well and we're happy with it:

- [ ] Roll out to other repos

### Description before 21/03/24

<details><summary>A table of repos and settings</summary>
This table is still forming ☃️ and is open to objections.  It also doesn't track updating the default branch for each, which was completed by:

- #19

GitHub doesn't seem to allow Markdown TODOs to work inside a table (let me know if you know how), and the outliner version of this table would have been very very long, so I'll settle here for:

`⏳ or empty` Pending
`🗣️` Discuss
`✅` Done

| Repo | Auto-delete head branches | Limit refs per push to `3` | Website as `https://pa11y.org` | `Releases` | `Packages` | Clean webhooks | 
|--|--|--|--|--|--|--|
| [pa11y/org](https://github.com/pa11y/org) | ✅ | ✅ | ✅ | ✅ Hide | ✅ Hide |
| [pa11y/pa11y.github.io](https://github.com/pa11y/pa11y.github.io) | 
| [pa11y/pa11y](https://github.com/pa11y/pa11y) |
| [pa11y/pa11y-ci](https://github.com/pa11y/pa11y-ci) | | ✅ | ✅ | ✅ Show | ✅ Hide |
| [pa11y/pa11y-dashboard](https://github.com/pa11y/pa11y-dashboard) | 
| [pa11y/pa11y-lint-config](https://github.com/pa11y/pa11y-lint-config) | 
| [pa11y/pa11y-webservice](https://github.com/pa11y/pa11y-webservice) | 
| [pa11y/pa11y-webservice-client-node](https://github.com/pa11y/pa11y-webservice-client-node) |
</details>

**Comment by josebolos** [comment]
Sounds good, I'm all up for having all the repos with the exact same settings 👍

**Comment by danyalaytekin** [comment]
@josebolos Definitely agree where it makes sense, branch protection rules and so on. A couple might differ, such as showing or not showing the 'packages' section. The presence is informative.

[github/safe-settings](https://github.com/github/safe-settings) may be the best option to centralise the ones we'd like to keep the same (and then we can delete my ill-fated table).  There are others, but they all require some security compromise.

Also spotted this, '[default community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)'.  But I can't see where the defaults actually surface:

- e.g. `dlang`
    - [defaults repo](https://github.com/dlang/.github)
    - [other repo](https://github.com/dlang/tools) which doesn't have its own e.g. `FUNDING.yml` (edit: ah, is it that section on the right?)

**Comment by hollsk** [comment]
Github's safe settings thing seems fine to use to me. 

Default community health files probably not needed as we've already got our own CONTRIBUTING.md file that links out to all that stuff on the Pa11y website. Think the only repo that doesn't have it is this one, and that's because we've never really expected community contributions to this one (even it was very active, which it isn't).

**Comment by danyalaytekin** [comment]
Great, thanks @hollsk.  I'll update the description of this ticket with some tasks for the implementation of safe settings and we could implement it for the linting config's repo initially to see how it goes.
