### ISSUE TITLE
Drop Node.js 0.10–0.12

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/org#6]
In order to drop support for Node.js 0.10–0.12 going forward, we'll need to coordinate major version bumps of all of our big projects. This shouldn't be too difficult, we just need to do it in order.

Separate issues have been raised in each repository. This issue should be used to track progress.
1. [x] Release [pa11y](https://github.com/pa11y/pa11y) `4.0` ([issue](https://github.com/pa11y/pa11y/issues/159))
2. [x] Release [pa11y-webservice](https://github.com/pa11y/pa11y-webservice) `2.0` ([issue](https://github.com/pa11y/pa11y-webservice/issues/27)), which should depend on pa11y `4.0`
3. [x] Release [pa11y-dashboard](https://github.com/pa11y/pa11y-dashboard) `2.0` ([issue](https://github.com/pa11y/pa11y-dashboard/issues/133)), which should depend on pa11y-webservice `2.0`

Outside of these main projects, we also have two others which currently support older versions of Node.js. These should be updated as well, but there's no urgency.
- [ ] [pa11y-webservice-client-node](https://github.com/pa11y/pa11y-webservice-client-node)
- [ ] [pa11y-reporter-1.0-json](https://github.com/pa11y/pa11y-reporter-1.0-json)

If we time these releases correctly and set matching support-end dates, then we should no longer have to worry about Node.js 0.10–0.12 from early to mid December 2016.

New projects will only support Node.js 4+.

**Comment by josebolos** [comment]
This is now done.
